### ISSUE TITLE
Suggestion: the FAB location should be slightly changed so that it fits within the magins of the background. 

### ISSUE THREAD

**Issue by osjasmine** [Glitchy-Tozier/githo#10]
![23fd24b1-4570-4cf0-aadd-0f677d3c0094.jpg](https://user-images.githubusercontent.com/86544869/132045371-80d372f6-b9ef-48f1-b03a-616b55a7f1b4.jpg)

I have marked in red what I mean by margins. As you can see the + button is slightly outside the margin. 
I think it should be moved so that it is inside the margin.

**Comment by Glitchy-Tozier** [comment]
So in your opinion it would be better if it perfectly hit the border of the two zones?

I'll play around with the margins and will see what I can do!  :+1:

**Comment by Glitchy-Tozier** [comment]
Done, you'll see the change once I've fixed one or two other things and released the app on F-Droid.

**Comment by osjasmine** [comment]
Thank you so much for conidering my suggestion and thank you for making this FOSS app!
