### ISSUE TITLE
Ability to activate multiple habit-plans at once

### ISSUE THREAD

**Issue by newissuemaker** [Glitchy-Tozier/githo#13]
I'm currently trying to get used to work on multiple things. However the app doesn't let me activate multiple habit plans. I can just use pen and paper for example but having the ability to do this on the app would be very nice. Thank you for reading.

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your request. This is a duplicate of #6, please read trough my response on that issue. I home it makes sense.
