### ISSUE TITLE
Feature request: Notifications

### ISSUE THREAD

**Issue by baltevl** [Glitchy-Tozier/githo#17]
Notifications as a reminder with the possiblity to turn them off and to set a time when to notify.

**Comment by Glitchy-Tozier** [comment]
Thank you for your feature request!
I, too, was thinking this might be a great addition to the app. Will see what I can do. It might take a few weeks though.

**Comment by Glitchy-Tozier** [comment]
Notifications have been added. They will be available once the new update gets released (most likely within the next 2 weeks).

**Comment by EmiliaBlasten** [comment]
The notification just buzzes my phone and does not leave any visible message in the notification tab. If I miss the buzz there is no way for me to see that I was supposed to do something unless I explicitly open the app.

I have notifications enabled:
![Screenshot_20220413-112128](https://user-images.githubusercontent.com/46397121/163202929-c46f149c-ef12-4b8a-9cd2-d4145f94e040.png)
![Screenshot_20220413-112142](https://user-images.githubusercontent.com/46397121/163202972-84b39ae8-c5c7-43d8-a2fa-5a7f3f32fa79.png)

The Android notifications tab does not display anything related to the app:
![Screenshot_20220413-112313](https://user-images.githubusercontent.com/46397121/163203006-cd17320d-7ef2-430e-8ab1-bdaa7eebf2b6.png)

I am running version 1.3.2 from F-Droid.
