### ISSUE TITLE
does this app work for "reductive" habits?

### ISSUE THREAD

**Issue by leleleSDX** [Glitchy-Tozier/githo#22]
the app works for adding habits like jogging exercise etc. but for reducing bad habits like smoking, overeating, spending? let's say you want to reduce your calorie intake from 2500 to 1000 gradually?

**Comment by Glitchy-Tozier** [comment]
There is no dedicated "reducing-mode", but you could still formulate goals and steps in a sensible manner:
- Goal: 1000 calories
- Steps:
  1. 2000 calories
  1. 1500 calories
  1. 1000 calories

**Comment by Glitchy-Tozier** [comment]
I hope i could sufficiently answer your question. Should there be anything else regarding this topic, you're welcome to re-open this issue!
