### ISSUE TITLE
Undo an accidental tick.

### ISSUE THREAD

**Issue by Long-FA** [Glitchy-Tozier/githo#7]
In the current version of Githo, if an user accidentally tick the checkbox, there is no way to undo that. They would have to clear the entire progression and start over again.
My suggestion: Holding the checkbox will reset the value back to zero.

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your proposal. I really like it, and I like the thought of long-press being used (maybe with a red splash-effect).
The only thing I might change is that long-press reduces the count by 1 rep instead of completely resetting the value to zero.

Will place it on the to-do list!

**Comment by Glitchy-Tozier** [comment]
I have implemented this feature in https://github.com/Glitchy-Tozier/githo/commit/63894ef2a71fe00a97ca1822e74bb46930dc76ea.

Depending on when F-Droid gets un-stuck, the update should be available in a few days to a week.

**Comment by Long-FA** [comment]
Appreciate that. I will try it once it lands on F-droid.
Aug 21, 2021, 13:46 by ***@***.***:

>
>
>
>
>
> I have implemented this feature in > 63894ef> .
>
>
>
> Depending on when F-Droid gets un-stuck, the update should be available in a few days to a week.
>
>
